<!doctype html>
<html>
<head>
    <title>WWR panel administracyjny</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content="674333452690-oqakalh87637ojol3g6h1383aeppqvot.apps.googleusercontent.com">


</head>

<body class="bg-light">
<main>
    <h1>Panel administracyjny</h1>
</main>
</body>
</html>