<!DOCTYPE html>
<html>
<head>
</head>
<body>
<h1>Znajdź najbliższe placówki rehabilitacyjne pacjenta</h1>
<form name="patientsFacilities">
    <input type="text" name="name" onkeyup="searchInfo()">
</form>

<span id="mylocation"></span>

<script src="https://code.jquery.com/jquery-1.10.2.js"
        type="text/javascript"></script>
<script src="/find-facilities-by-patient.js"></script>

</body>
</html>